put setup instructions into README
rokka-io/rokka-client-php pull request #11
Opened 2016-10-27 15:35 UTC by dbu

2017-02-23 09:49 UTC, michellesanver requested changes

2017-02-23 09:49 UTC, michellesanver commented on README.md
> +See the [official documentation](https://rokka.io/documentation) on how to use the Rokka API.
This is a bit confusing for the user, but that means we should probably change the rokka.io documentation, if we do that this line can stay.

2017-02-23 09:49 UTC, michellesanver commented on README.md
> +You will need to create an account on Rokka to get your api key and secret and create an organization.
In this sprint the organization will be created automatically when you sign up. So maybe the best line here would be "You will need to register for a Rokka account and use the api key and secret that you recieved" it doesn't have to mention the "create an organization" step.

2017-02-23 09:54 UTC, michellesanver commented on README.md
> +See the [official documentation](https://rokka.io/documentation) on how to use the Rokka API.
Actually could change this line to "on how to use the Rokka API with curl examples" for now and open up a ticket to make PHP examples in that doc and then change this line.

2017-02-23 10:15 UTC, chregu commented
lots of php code examples are also on rokka.io/documentatino, btw...

2017-02-28 07:44 UTC, dbu commented on README.md
> +See the [official documentation](https://rokka.io/documentation) on how to use the Rokka API.
there are php examples e.g. on https://rokka.io/documentation/references/memberships.html - imo that is good enough for now. i would merge the readme as is and then work on the documentation side at some point. for example the tabs approach for code examples.

2017-02-28 07:47 UTC, closed without merging

2017-02-28 07:49 UTC, dbu commented
no idea what was going on with github here, had to re-create the PR as #21